CREATE TABLE IF NOT EXISTS presupuesto(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    concepto text NOT NULL,
    monto decimal NOT NULL,
    fecha date NOT NULL,
    tipo text NOT NULL
);

INSERT INTO presupuesto(concepto, monto, fecha, tipo)
    VALUES ('Cobro de sueldo', 20000, '2021-10-01', 'Ingreso');